Update scripts

diff --git a/scripts b/scripts
--- a/scripts
+++ b/scripts
@@ -176,3 +176,107 @@ ansible installation by enabling the epel(download rpm package and do rpm -ivh p
         unzip awscli-bundle.zip
         sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
         echo "AWS Cli Installation completed"
+
+
+
+
+        to connect to the no.of servers
+	================================
+	
+	
+	#!/bin/bash
+
+        oslist=filename
+
+        for serername in `cat /opt/scripts/serverlist`
+        #Connecting to remote servers
+
+        ssh devopsadmin@$servername
+        #redirecting output of uname into filename
+        uname >>$oslist
+
+        done
+
+        #priting the os list file
+        cat $oslist
+        #send the email with subject with attachment(filename)
+        mail -s "OS lists" someone@somewhere.com -a $oslist
+
+
+        o/p:
+        ====
+
+
+
+
+
+        ping 
+        ====
+
+        #!/bin/sh
+ 
+        # -q quiet
+        # -c nb of pings to perform
+        echo "enter the name"
+        read name
+        ping -q -c5 $name > /dev/null
+       
+        #check previous command successful or not
+        if  [$? -eq 0 ]
+        then
+        echo "ok"
+        fi
+
+
+
+        o/p:
+        ====
+
+        enter the name
+        google.com
+        ok
+
+
+
+
+        ping with multiple websites
+        ============================
+
+
+        #!/bin/bash
+        webs=/home/devopsadmin/scripts/websites                                             or /serverslist
+
+        for name in `cat $webs`; do 
+        ping -q -c5 $name > /dev/null
+
+        if [ $? -eq 0 ]; then
+        echo "$name --> OK "
+        else
+        echo "$name-->FAIL"
+        fi
+        done
+
+
+
+
+        o/p:
+        =====
+
+        www.google.com --> OK
+        webserver-->FAIL
+        nginx-->FAIL
+
+
+
+        #!/bin/bash
+        for i in `sec 0 255`; do 
+        ping -c 1 $i >/dev/null 2>&1 
+        if [ "$?" = "0" ]; then 
+        echo -n "up" 
+        else echo -n "down" 
+        fi
+        done
+
+
+        o/p:
+        =====
